### ISSUE TITLE
کمپایل نشدن برنامه با دات نت 5

### ISSUE THREAD

**Issue by KomeilParseh** [ganjoor/ganjoor#4]
## کمپایل نشدن برنامه با دات نت 5
سلام به شما من در لینوکس بعد از نصب دات نت  و ... با کمپایل کردن برنامه میگه که **نسخه 4.7.2** باید داشته باشی که نداری منم نمیتونم پیدا کنم، شاید من اشتباه میکنم شاید هم برنامه پشتیبانی نمیکنه.
ممنون میشم که به من کمک کنید که از این برنامه عالی استفاده کنم
پ.ن. من **دات نت** بلد نیستم!

**با تشکر کمیل پارسه**

**Comment by hrmoh** [comment]
سلام
برنامه با
.NET Framework 4.7.2
آماده شده.
سازگاری و کامپایل آن با
.NET 5.0
احتمالا مستلزم تغییراتی در کد باشد.

**Comment by KomeilParseh** [comment]
ممنون از شما
