### ISSUE TITLE
Texts and Highlights!

### ISSUE THREAD

**Issue by Aquarii** [ganjoor/ganjoor#5]
سلام. 
نمیشه متنا رو تکست کنید ک بشه انتخابشون کرد؟
و اگه ی هایلات هم بشه بغل نشانه‌ها اضافه کرد عالیه. ک هایلایت کنی و در قسمت نشانه‌ها به هایلایتهات دسترسی داشته باشی.
دمتون گرم.

**Comment by hrmoh** [comment]
سلام
نه متأسفانه
برای این قابلیت از ساعر استفاده کنید:
http://pozh.org/saaghar/
